### PR TITLE
Implemented SBD Printing Percentage

### PR DESCRIPTION
**Pull request by therealwolf42**

### CODE REVIEW

**Comment by AusPrinzip** [comment]
The dsteem 'get_reward_fund' method you are applying in the new proposed function 'getVoteValueUSD'  doesn't return a 'sbd_print_rate' attribute.

Just tested and the returned object is as follows:

> { id: 0,
  name: 'post',
  reward_balance: '832364.778 STEEM',
  recent_claims: '546997829206368293',
  last_update: '2018-12-06T17:57:33',
  content_constant: '2000000000000',
  percent_curation_rewards: 2500,
  percent_content_rewards: 10000,
  author_reward_curve: 'linear',
  curation_reward_curve: 'square_root' }

>

**Comment by therealwolf42** [comment]
image

https://github.com/MattyIce/postpromoter/blob/0571d3fa6df9f682f57f2109e36860a6364aa61d/utils.js#L37

**Comment by AusPrinzip** [comment]
> image
> 
> [postpromoter/utils.js](https://github.com/MattyIce/postpromoter/blob/0571d3fa6df9f682f57f2109e36860a6364aa61d/utils.js#L37)
> 
> Line 37 in [0571d3f](/MattyIce/postpromoter/commit/0571d3fa6df9f682f57f2109e36860a6364aa61d)
> 
>  sbd_print_percentage = t.sbd_print_rate / 10000

Awesome, thanks for the clarification.

**Comment by therealwolf42** [comment]
No problem :)

**Comment by AusPrinzip** [comment]
In my last PR I forgot something useful you might want update (since your PR has not been accepted yet).

I would do it myself, but since @MattyIce seems pretty busy I would rather suggest it to you.

By updating the version we can check via API whether bot owners are running the latest patch.

https://github.com/MattyIce/postpromoter/blob/9bce0e0819f6a8a7845f5d3b87084e178d1dde1f/postpromoter.js#L23

**Comment by therealwolf42** [comment]
@AusPrinzip interesting, but I'm not using post promoter, so a version number won't mean anything in that case.

**Pull request merged**
